### PR TITLE
Fixes #31

### LINKED ISSUE #31: Too relaxed value validator?
I just noticed this behavior:
```js
> bytes('250Kg');
250
> bytes('250 e-mails');
250
```

Is this a bug? I would expect a `NaN` instead of `250B`, like in this example:
```js
> bytes('something 250');
NaN
```

### PR DESCRIPTION
**Pull request by theofidry**
Fixes #31.

### CODE REVIEW

**Comment by dougwilson** [comment]
Cool. This is going to be considered a major version bump, in my mind, due to the regular expression parsing change. For example, "3 bytes" would have worked before, but now it needs to be just "3b"

**Comment by theofidry** [comment]
Fair enough. Hacky way to use it but way to use it nonetheless.

**Comment by dougwilson** [comment]
I agree, which is why I'm :+1: for making the parsing stricter :)

**Comment by dougwilson** [comment]
Plus, there are a bunch of changes all mixed together in this pull request that can get released as a last 2.x, which should be good to have. For example, the `.forma(NaN)` fix.

**Pull request closed without merging**
